name: linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ '*' ]

jobs:

  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
        - '5.10-buster'
        - '5.12-buster'
        - '5.14-buster'
        - '5.16-buster'
        - '5.18-buster'
        - '5.20-buster'
        - '5.22-buster'
        - '5.24-buster'
        - '5.26-buster'
        - '5.28-buster'
        - '5.30-bullseye'
        - '5.32-bullseye'
        - '5.34-bullseye'
        - '5.36-bookworm'
        - '5.38-bookworm'
        - 'latest'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
    - uses: actions/checkout@v3
    - run: env | sort
    - run: perl -V
    - name: Install deps
      run: >
        cpanm --quiet --notest File::Which Test::More
    - name: Run Tests
      run: prove -lr t

  author-tests:
    runs-on: ubuntu-latest
    container:
      image: perl:5.38

    steps:
    - uses: actions/checkout@v3
    - run: env | sort
    - run: perl -V
    - name: Install deps
      run: >
        apt-get update && apt-get install -y aspell

        cpanm --quiet --notest Pod::Spell Test::Spelling Test::Pod
    - name: Run Tests
      run: prove -lv xt/03.spelling.t xt/04.pod.t
