name: macos

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  perl:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Perl
      run: brew install perl
    - name: perl -V
      run: perl -V

    - name: Install deps
      run: |
        curl -L https://cpanmin.us >cpanm && chmod +x cpanm
        ./cpanm --quiet --notest File::Which Test::More
    - name: Run Tests
      run: prove -lrv t
