name: windows

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  perl:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Perl
      run: |
        choco install strawberryperl
        echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: perl -V
      run: perl -V
    - name: Install deps
      run: |
        cpanm --quiet --notest File::Which Test::More
    - name: Run Tests
      run: prove -lrv t

